[package]
name = "raytracing_series"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rayon = "1.9.0"
rand = "0.8.5"
image = "0.25.5"